# Form implementation generated from reading ui file 'login_window.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form_login(object):
    def setupUi(self, Form_login):
        Form_login.setObjectName("Form_login")
        Form_login.resize(600, 666)
        Form_login.setMinimumSize(QtCore.QSize(300, 300))
        Form_login.setMaximumSize(QtCore.QSize(600, 800))
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(Form_login)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.widget = QtWidgets.QWidget(parent=Form_login)
        self.widget.setStyleSheet("background-color: qlineargradient(spread:reflect, x1:0, y1:1, x2:1, y2:0, stop:0 rgba(217, 76, 81, 255), stop:1 rgba(255, 255, 255, 255));\n"
"border-radius:15px;")
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(parent=self.widget)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(255, 255, 255);")
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.verticalLayout_3.addWidget(self.widget)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setContentsMargins(25, 15, 25, 40)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.lineEdit_username = QtWidgets.QLineEdit(parent=Form_login)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_username.setFont(font)
        self.lineEdit_username.setObjectName("lineEdit_username")
        self.verticalLayout_2.addWidget(self.lineEdit_username)
        self.lineEdit_password = QtWidgets.QLineEdit(parent=Form_login)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_password.setFont(font)
        self.lineEdit_password.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.lineEdit_password.setObjectName("lineEdit_password")
        self.verticalLayout_2.addWidget(self.lineEdit_password)
        self.cb_show_pwd = QtWidgets.QCheckBox(parent=Form_login)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.cb_show_pwd.setFont(font)
        self.cb_show_pwd.setObjectName("cb_show_pwd")
        self.verticalLayout_2.addWidget(self.cb_show_pwd)
        self.pushButton_login = QtWidgets.QPushButton(parent=Form_login)
        self.pushButton_login.setMinimumSize(QtCore.QSize(20, 50))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton_login.setFont(font)
        self.pushButton_login.setStyleSheet("background-color: rgb(218, 79, 84);\n"
"color: rgb(255, 255, 255);\n"
"border-radius:10px;")
        self.pushButton_login.setObjectName("pushButton_login")
        self.verticalLayout_2.addWidget(self.pushButton_login)
        self.verticalLayout_3.addLayout(self.verticalLayout_2)

        self.retranslateUi(Form_login)
        QtCore.QMetaObject.connectSlotsByName(Form_login)

    def retranslateUi(self, Form_login):
        _translate = QtCore.QCoreApplication.translate
        Form_login.setWindowTitle(_translate("Form_login", "Giriş Ekranı"))
        self.label.setText(_translate("Form_login", "ÇOCUK GELİŞİM AKADEMİSİ GİRİŞ"))
        self.lineEdit_username.setPlaceholderText(_translate("Form_login", "Kullanıcı Adı"))
        self.lineEdit_password.setPlaceholderText(_translate("Form_login", "Şifre"))
        self.cb_show_pwd.setText(_translate("Form_login", "Şifre Göster"))
        self.pushButton_login.setText(_translate("Form_login", "Giriş"))
